# Simplified Chinese translation for gdebi
# Copyright (c) 2007 Rosetta Contributors and Canonical Ltd 2007
# This file is distributed under the same license as the gdebi package.
# rainofchaos <rainofchaos@gmail.com>, 2007.
# rainofchaos <rainofchaos@gmail.com>, 2008.
#
#
msgid ""
msgstr ""
"Project-Id-Version: gdebi\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2011-01-31 21:35+0100\n"
"PO-Revision-Date: 2011-03-20 06:32+0000\n"
"Last-Translator: 英华 <wantinghard@gmail.com>\n"
"Language-Team: Simplified Chinese <zh_CN@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2011-03-31 21:08+0000\n"
"X-Generator: Launchpad (build 12696)\n"

#: ../gdebi:47
#, c-format
msgid ""
"usage: %prog [options] filename\n"
"For a graphical version run gdebi-gtk\n"
msgstr ""
"用法：%prog [选项] 文件名\n"
"要使用图形化版本，可以运行 gdebi-gtk\n"

#: ../gdebi:53 ../gdebi-gtk:53
msgid "Run non-interactive (dangerous!)"
msgstr "以非交互式运行（危险！）"

#: ../gdebi:57
msgid "Set an APT configuration option"
msgstr "设置一个 APT 配置选项"

#: ../gdebi:61
msgid "Do not show progress information"
msgstr "不显示进度信息"

#: ../gdebi:65
msgid "Simulate only and print a apt-get install compatible line to stderr"
msgstr "仅模拟执行并向标准错误（stderr）输出一行与 apt-get install 兼容的信息。"

#: ../gdebi:67
msgid "Use alternative root dir"
msgstr "使用另外的 root 文件夹"

#: ../gdebi:75
#, c-format
msgid "gdebi error, file not found: %s\n"
msgstr "gdebi 错误，找不到文件：%s\n"

#: ../gdebi:94 ../gdebi:104
msgid "Need to be root to install packages"
msgstr "需要以 root 权限安装软件包"

#: ../gdebi:106 ../GDebi/GDebiCli.py:154
msgid "Do you want to install the software package? [y/N]:"
msgstr "您是否想安装这个软件包？[y/N]:"

#: ../gdebi-gtk:56
msgid "Auto close when the install is finished"
msgstr "安装完成后自动关闭"

#: ../gdebi-gtk:58
msgid "Use alternative datadir"
msgstr "使用另外的数据路径"

#: ../gdebi-gtk:77
msgid "Software index is broken"
msgstr "软件索引已损坏"

#: ../gdebi-gtk:78
msgid ""
"This is a major failure of your software management system. Please check for "
"broken packages with synaptic, check the file permissions and correctness of "
"the file '/etc/apt/sources.list' and reload the software information with: "
"'sudo apt-get update' and 'sudo apt-get install -f'."
msgstr ""
"这是您软件管理系统的重大失败。请使用新立得检查损坏的软件包，检查文件权限和 '/etc/apt/sources.list' 文件的正确性并使用 "
"'sudo apt-get update' 和 'sudo apt-get install -f' 重新载入软件信息。"

#: ../data/gdebi.ui.h:1
msgid "  "
msgstr "  "

#: ../data/gdebi.ui.h:2
msgid "<b><big>   </big></b>"
msgstr "<b><big> </big></b>"

#: ../data/gdebi.ui.h:3 ../GDebi/GDebiKDE.py:140
msgid "<b>Maintainer:</b>"
msgstr "<b>维护者：</b>"

#: ../data/gdebi.ui.h:4 ../GDebi/GDebiKDE.py:141
msgid "<b>Priority:</b>"
msgstr "<b>优先级：</b>"

#: ../data/gdebi.ui.h:5 ../GDebi/GDebiKDE.py:142
msgid "<b>Section:</b>"
msgstr "<b>组别：</b>"

#: ../data/gdebi.ui.h:6 ../GDebi/GDebiKDE.py:143
msgid "<b>Size:</b>"
msgstr "<b>大小：</b>"

#: ../data/gdebi.ui.h:7 ../GDebi/GDebiKDE.py:280
msgid "<b>To install the following changes are required:</b>"
msgstr "<b>要进行安装，需要做以下改变：</b>"

#: ../data/gdebi.ui.h:8 ../GDebi/GDebiKDE.py:139
msgid "<b>Version:</b>"
msgstr "<b>版本：</b>"

#: ../data/gdebi.ui.h:9
msgid "Automatically close after the changes have been successfully applied"
msgstr "在成功应用更改后自动关闭"

#: ../data/gdebi.ui.h:10 ../GDebi/GDebiKDE.py:134
msgid "Description"
msgstr "描述"

#: ../data/gdebi.ui.h:11
msgid "Description:"
msgstr "描述："

#: ../data/gdebi.ui.h:12 ../GDebi/GDebiKDE.py:133 ../GDebi/GDebiKDE.py:135
#: ../GDebi/GDebiKDE.py:281
msgid "Details"
msgstr "细节"

#: ../data/gdebi.ui.h:13
msgid "GPL, see /usr/share/common-licenses/GPL"
msgstr "GPL, 参见 /usr/share/common-licenses/GPL"

#: ../data/gdebi.ui.h:14
msgid "Included files"
msgstr "包含的文件"

#: ../data/gdebi.ui.h:15 ../data/gdebi.desktop.in.h:2
msgid "Install and view software packages"
msgstr "安装和查看软件包"

#: ../data/gdebi.ui.h:16 ../data/gdebi.desktop.in.h:3
msgid "Package Installer"
msgstr "软件包安装程序"

#. first, we load all the default descriptions -- pyuic doesn't use
#. gettext as default (FIXME, copy code from language-selector)
#: ../data/gdebi.ui.h:17 ../GDebi/GDebiKDE.py:131
msgid "Package:"
msgstr "软件包："

#: ../data/gdebi.ui.h:18 ../GDebi/GDebiKDE.py:132
msgid "Status:"
msgstr "状态:"

#: ../data/gdebi.ui.h:19
msgid "Terminal"
msgstr "终端"

#: ../data/gdebi.ui.h:20
msgid "_Details"
msgstr "细节(_D)"

#: ../data/gdebi.ui.h:21
msgid "_File"
msgstr "文件(_F)"

#: ../data/gdebi.ui.h:22
msgid "_Help"
msgstr "帮助(_H)"

#. img = gtk.Image()
#. img.set_from_stock(gtk.STOCK_APPLY,gtk.ICON_SIZE_BUTTON)
#. self.button_install.set_image(img)
#: ../data/gdebi.ui.h:23 ../GDebi/GDebi.py:308 ../GDebi/GDebi.py:348
msgid "_Install Package"
msgstr "安装软件包(_I)"

#: ../data/gdebi.ui.h:24
msgid "_Open..."
msgstr "打开(_O)..."

#: ../data/gdebi.ui.h:25
msgid "_Refresh"
msgstr "刷新(_R)"

#: ../data/gdebi.xml.in.h:1
msgid "Software package"
msgstr "软件包"

#: ../data/gdebi.desktop.in.h:1
msgid "GDebi Package Installer"
msgstr "GDebi 软件包安装程序"

#. Translators: it's for missing entries in the deb package,
#. e.g. a missing "Maintainer" field
#: ../GDebi/DebPackage.py:38
#, python-format
msgid "%s is not available"
msgstr "%s 不可用"

#: ../GDebi/GDebi.py:90
msgid "Loading..."
msgstr "正在加载..."

#: ../GDebi/GDebi.py:167
msgid "Can not download as root"
msgstr "无法以 root 身份下载"

#: ../GDebi/GDebi.py:168
msgid ""
"Remote packages can not be downloaded when running as root. Please try again "
"as a normal user."
msgstr "以 root 身份运行时无法下载远程软件包。请以普通用户身份重试。"

#: ../GDebi/GDebi.py:181
msgid "Downloading package"
msgstr "正在下载软件包"

#: ../GDebi/GDebi.py:188
msgid "Download failed"
msgstr "下载失败"

#: ../GDebi/GDebi.py:189
#, python-format
msgid "Downloading the package failed: file '%s' '%s'"
msgstr "软件包下载失败：文件 '%s' '%s'"

#. set window title
#. set name
#: ../GDebi/GDebi.py:228 ../GDebi/GDebiKDE.py:181
#, python-format
msgid "Package Installer - %s"
msgstr "软件包安装程序 - %s"

#: ../GDebi/GDebi.py:285
msgid "Package control data"
msgstr "软件包控制数据"

#: ../GDebi/GDebi.py:288
msgid "Upstream data"
msgstr "上游数据"

#: ../GDebi/GDebi.py:294
msgid "Error reading filelist"
msgstr "读取文件列表出错"

#: ../GDebi/GDebi.py:305
msgid "Error: "
msgstr "错误： "

#: ../GDebi/GDebi.py:320
msgid "Same version is already installed"
msgstr "已安装相同版本"

#: ../GDebi/GDebi.py:321
msgid "_Reinstall Package"
msgstr "重新安装软件包(_R)"

#: ../GDebi/GDebi.py:364
msgid "Selection is a directory"
msgstr "选择的是一个目录"

#: ../GDebi/GDebi.py:369 ../GDebi/GDebi.py:374
#, python-format
msgid "Error reading file content '%s'"
msgstr "读取文件内容“%s”时出错"

#: ../GDebi/GDebi.py:378
msgid "File content can not be extracted"
msgstr "无法提取文件内容"

#: ../GDebi/GDebi.py:389
#, python-format
msgid "<b>To be removed: %s</b>"
msgstr "<b>将要删除：%s</b>"

#: ../GDebi/GDebi.py:391 ../GDebi/GDebiKDE.py:275
#, python-format
msgid "To be installed: %s"
msgstr "将要安装：%s"

#: ../GDebi/GDebi.py:406
msgid "Open Software Package"
msgstr "打开软件包"

#: ../GDebi/GDebi.py:411
msgid "Software packages"
msgstr "软件包"

#: ../GDebi/GDebi.py:440
msgid "File not found"
msgstr "文件未找到"

#: ../GDebi/GDebi.py:441
msgid "You tried to install a file that does not (or no longer) exist. "
msgstr "您试图安装一个不存在(或不再存在)的文件。 "

#. do it
#: ../GDebi/GDebi.py:451
msgid "Installing package file..."
msgstr "正在安装软件包文件..."

#: ../GDebi/GDebi.py:453
msgid "Install unauthenticated software?"
msgstr "安装未认证的软件？"

#: ../GDebi/GDebi.py:454
msgid ""
"Malicious software can damage your data and take control of your system.\n"
"\n"
"The packages below are not authenticated and could therefore be of malicious "
"nature."
msgstr ""
"恶意软件会破坏您的数据并控制您的系统。\n"
"\n"
"以下的软件包未经过验证，可能会具有恶意性质。"

#: ../GDebi/GDebi.py:481
msgid "You need to grant administrative rights to install software"
msgstr "你需要获取管理员权限以安装软件"

#: ../GDebi/GDebi.py:482
msgid ""
"\n"
"It is a possible security risk to install packages files manually.\n"
"Install software from trustworthy software distributors only.\n"
msgstr ""
"\n"
"手工安装软件包是一种潜在的安全风险。\n"
"只从值得信任的软件发行者的渠道安装软件。\n"

#: ../GDebi/GDebi.py:505 ../GDebi/GDebi.py:564
msgid "Failed to install package file"
msgstr "安装软件包文件失败"

#: ../GDebi/GDebi.py:548 ../GDebi/GDebiKDE.py:327
msgid "Could not download all required files"
msgstr "无法下载全部必需的文件"

#: ../GDebi/GDebi.py:549 ../GDebi/GDebiKDE.py:328
msgid "Please check your internet connection or installation medium."
msgstr "请检查您的互联网连接或安装介质。"

#: ../GDebi/GDebi.py:553 ../GDebi/GDebiKDE.py:332
msgid "Could not install all dependencies"
msgstr "无法安装所有依赖软件包"

#: ../GDebi/GDebi.py:554 ../GDebi/GDebiKDE.py:333
msgid ""
"Usually this is related to an error of the software distributor. See the "
"terminal window for more details."
msgstr "通常这与软件发行者的一个错误有关。查看终端窗口输出获取更多细节。"

#: ../GDebi/GDebi.py:570
#, python-format
msgid "Installing %s"
msgstr "正在安装 %s"

#. self.label_action.set_markup("<b><big>"+_("Package installed")+"</big></b>")
#. show the button
#. self.button_deb_install_close.set_sensitive(True)
#. self.button_deb_install_close.grab_default()
#: ../GDebi/GDebi.py:586 ../GDebi/GDebiKDE.py:352
msgid "Installation finished"
msgstr "安装完成"

#: ../GDebi/GDebi.py:588
#, python-format
msgid "Package '%s' was installed"
msgstr "软件包'%s'已安装"

#: ../GDebi/GDebi.py:590 ../GDebi/GDebiKDE.py:356
#, python-format
msgid "Failed to install package '%s'"
msgstr "安装软件包'%s'失败"

#: ../GDebi/GDebi.py:592
msgid "Installation complete"
msgstr "安装完成"

#: ../GDebi/GDebi.py:599 ../GDebi/GDebiKDE.py:366
msgid "Failed to completely install all dependencies"
msgstr "未能完整地安装所有依赖软件包"

#: ../GDebi/GDebi.py:600 ../GDebi/GDebiKDE.py:367
msgid "To fix this run 'sudo apt-get install -f' in a terminal window."
msgstr "要修复，在终端窗口中运行 'sudo apt-get install -f' 。"

#. ui
#: ../GDebi/GDebi.py:695 ../GDebi/KDEAptDialogs.py:73
#, python-format
msgid "Installing '%s'..."
msgstr "正在安装 '%s'..."

#: ../GDebi/GDebi.py:785 ../GDebi/KDEAptDialogs.py:141
msgid "Installing dependencies..."
msgstr "正在安装依赖软件包..."

#: ../GDebi/GDebi.py:823 ../GDebi/KDEAptDialogs.py:204
#: ../GDebi/KDEAptDialogs.py:217 ../GDebi/KDEAptDialogs.py:219
msgid "Downloading additional package files..."
msgstr "正在下载额外的软件包文件..."

#: ../GDebi/GDebi.py:832 ../GDebi/KDEAptDialogs.py:217
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "文件 %s/%s 速度： %sB/s"

#: ../GDebi/GDebi.py:834 ../GDebi/KDEAptDialogs.py:219
#, python-format
msgid "File %s of %s"
msgstr "文件 %s/%s"

#. print "mediaChange %s %s" % (medium, drive)
#: ../GDebi/GDebi.py:841 ../GDebi/KDEAptDialogs.py:224
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "请将 '%s' 插入驱动器 '%s' 中"

#: ../GDebi/GDebiCli.py:59
msgid "Configuration items must be specified with a =<value>\n"
msgstr "配置项必须以 =<值> 的方式指定\n"

#: ../GDebi/GDebiCli.py:65
#, python-format
msgid "Couldn't set APT option %s to %s\n"
msgstr "无法将 APT 选项 %s 设为 %s\n"

#: ../GDebi/GDebiCli.py:78
#, python-format
msgid "Unknown package type '%s', exiting\n"
msgstr "未知软件包类型 '%s'，退出\n"

#: ../GDebi/GDebiCli.py:81
msgid "Failed to open the software package\n"
msgstr "打开软件包失败\n"

#: ../GDebi/GDebiCli.py:82
msgid ""
"The package might be corrupted or you are not allowed to open the file. "
"Check the permissions of the file.\n"
msgstr "软件包可能已被破坏，或者不允许您打开此文件。检查文件的权限。\n"

#: ../GDebi/GDebiCli.py:88
msgid "This package is uninstallable\n"
msgstr "此软件包不可安装\n"

#: ../GDebi/GDebiCli.py:97 ../GDebi/GDebiKDE.py:217
msgid "No description is available"
msgstr "没有可用的描述"

#: ../GDebi/GDebiCli.py:103
msgid "The following packages are UNAUTHENTICATED: "
msgstr "下列软件包未经认证： "

#: ../GDebi/GDebiCli.py:107
msgid "Requires the REMOVAL of the following packages: "
msgstr "需要 移除 以下软件包： "

#: ../GDebi/GDebiCli.py:112
msgid "Requires the installation of the following packages: "
msgstr "需要安装以下软件包： "

#: ../GDebi/GDebiCli.py:126 ../GDebi/GDebiCli.py:129
#, python-format
msgid "Error during install: '%s'"
msgstr "安装时出错： '%s'"

#: ../GDebi/GDebiKDE.py:136
msgid "Included Files"
msgstr "包含文件"

#: ../GDebi/GDebiKDE.py:138 ../GDebi/GDebiKDE.py:263
msgid "&Install Package"
msgstr "安装软件包(&I)"

#: ../GDebi/GDebiKDE.py:162
msgid "The package file does not exist"
msgstr "软件包文件不存在"

#: ../GDebi/GDebiKDE.py:163
msgid ""
"A nonexistent file has been selected for installation. Please select an "
"existing .deb package file."
msgstr "选择了一个不存在的文件来安装。请选择一个存在的 .deb 软件包文件。"

#. self.textLabel1_3_2.setText(_("Same version is already installed"))
#: ../GDebi/GDebiKDE.py:231
msgid "&Reinstall Package"
msgstr "重新安装软件包(&R)"

#: ../GDebi/GDebiKDE.py:266
msgid "Re&install Package"
msgstr "重新安装软件包(&I)"

#: ../GDebi/GDebiKDE.py:277
#, python-format
msgid "To be removed: %s"
msgstr "要移除的： %s"

#: ../GDebi/GDebiKDE.py:354
msgid "<b>"
msgstr "<b>"

#: ../GDebi/GDebiCommon.py:67
msgid "Broken dependencies"
msgstr "损坏的依赖关系"

#: ../GDebi/GDebiCommon.py:68
msgid ""
"Your system has broken dependencies. This application can not continue until "
"this is fixed. To fix it run 'gksudo synaptic' or 'sudo apt-get install -f' "
"in a terminal window."
msgstr ""
"您的系统中存在损坏的依赖关系。不修复它此程序无法继续。要修复，在终端窗口中运行 'gksudo synaptic' 或 'sudo apt-get "
"install -f' 。"

#: ../GDebi/GDebiCommon.py:85
#, python-format
msgid "'%s' is not a Debian package"
msgstr "'%s' 不是一个 Debian 软件包"

#: ../GDebi/GDebiCommon.py:86
#, python-format
msgid ""
"The MIME type of this file is '%s' and can not be installed on this system."
msgstr "此文件的 MIME 类型为 '%s' ，不能安装到系统上。"

#: ../GDebi/GDebiCommon.py:90
#, python-format
msgid "Could not open '%s'"
msgstr "打不开 '%s'"

#: ../GDebi/GDebiCommon.py:91
msgid ""
"The package might be corrupted or you are not allowed to open the file. "
"Check the permissions of the file."
msgstr "软件包可能已损坏或不允许您打开此文件。检查文件的权限。"

#: ../GDebi/GDebiCommon.py:107
msgid "Same version is available in a software channel"
msgstr "软件仓库中有相同版本"

#: ../GDebi/GDebiCommon.py:108
msgid "You are recommended to install the software from the channel instead."
msgstr "建议您从软件仓库中安装这个软件。"

#: ../GDebi/GDebiCommon.py:112
msgid "An older version is available in a software channel"
msgstr "软件渠道中有较旧的可用版本。"

#: ../GDebi/GDebiCommon.py:113
msgid ""
"Generally you are recommended to install the version from the software "
"channel, since it is usually better supported."
msgstr "您最好还是从软件仓库中安装这个软件，因为它通常有更好的支持。"

#: ../GDebi/GDebiCommon.py:118
msgid "A later version is available in a software channel"
msgstr "软件仓库中有更新的版本"

#: ../GDebi/GDebiCommon.py:120
msgid ""
"You are strongly advised to install the version from the software channel, "
"since it is usually better supported."
msgstr "强烈建议您从软件仓库中安装这个软件，因为它通常有更好的支持。"

#: ../GDebi/GDebiCommon.py:128
msgid "All dependencies are satisfied"
msgstr "所有依赖关系已满足"

#. FIXME: use ngettext here
#: ../GDebi/GDebiCommon.py:131
#, python-format
msgid "Requires the <b>removal</b> of %s packages\n"
msgstr "需要 the <b>移除</b>  %s 个软件包\n"

#: ../GDebi/GDebiCommon.py:133
#, python-format
msgid "Requires the installation of %s packages"
msgstr "需要安装 %s 个软件包"

#: ../GDebi/GDebiCommon.py:141 ../GDebi/GDebiCommon.py:159
msgid "Only one software management tool is allowed to run at the same time"
msgstr "同时只允许运行一个软件管理工具"

#: ../GDebi/GDebiCommon.py:143 ../GDebi/GDebiCommon.py:161
msgid ""
"Please close the other application e.g. 'Update Manager', 'aptitude' or "
"'Synaptic' first."
msgstr "请先关闭其他应用程序如 'Update Manager'、 'aptitude' 或 'Synaptic' 。"

#. change = QMessageBox.question(None, _("Media Change"), msg, QMessageBox.Ok, QMessageBox.Cancel)
#: ../GDebi/KDEAptDialogs.py:226
msgid "Media Change"
msgstr "媒介改变"

#~ msgid "gdebi"
#~ msgstr "gdebi"

#, python-format
#~ msgid "Wrong architecture '%s'"
#~ msgstr "错误的架构 '%s'"

#~ msgid "translator-credits"
#~ msgstr ""
#~ "Launchpad Contributions:\n"
#~ "  Aron Xu https://launchpad.net/~happyaron\n"
#~ "  Careone https://launchpad.net/~zzbusagain\n"
#~ "  Colin Zhao https://launchpad.net/~colin-shzsc\n"
#~ "  Qiu Haoyu https://launchpad.net/~timothyqiu\n"
#~ "  Xhacker Liu https://launchpad.net/~xhacker\n"
#~ "  zhangmiao https://launchpad.net/~mymzhang\n"
#~ "  冯超 https://launchpad.net/~rainofchaos\n"
#~ "  英华 https://launchpad.net/~wantinghard"

#~ msgid "Y"
#~ msgstr "Y"

#~ msgid "Open..."
#~ msgstr "打开..."

#, python-format
#~ msgid "Dependency is not satisfiable: %s\n"
#~ msgstr "依赖关系不满足： %s\n"

#, python-format
#~ msgid "Conflicts with the installed package '%s'\n"
#~ msgstr "与已安装的软件包 '%s' 冲突\n"

#~ msgid "Analysing dependencies"
#~ msgstr "正在分析依赖关系"

#~ msgid "No Architecture field in the package"
#~ msgstr "软件包中没有 架构 字段信息"

#~ msgid ""
#~ "Malicous software can damage your data and take control of your system.\n"
#~ "\n"
#~ "The packages below are not authenticated and could therefor be of malicous "
#~ "nature."
#~ msgstr ""
#~ "恶意软件可能破坏您的数据和控制您的系统。\n"
#~ "\n"
#~ "下列软件包没有认证所以实质上可能是恶意软件。"

#~ msgid "A later version is already installed"
#~ msgstr "已经安装了较新的版本"

#, python-format
#~ msgid "Cannot install '%s'"
#~ msgstr "无法安装 '%s'"

#~ msgid "Failed to satisfy all dependencies (broken cache)"
#~ msgstr "满足所有依赖关系失败(缓存损坏)"

#, python-format
#~ msgid "IOError during filelist read: %s"
#~ msgstr "读取文件列表时发生 IO 错误： %s"

#~ msgid "List of files could not be read, please report this as a bug"
#~ msgstr "无法读取列出的文件，请将这作为错误提交"

#, python-format
#~ msgid "Breaks exisiting package '%s' conflict: %s (%s %s)\n"
#~ msgstr "残缺：软件包 '%s' 与 %s (%s %s) 冲突\n"

#, python-format
#~ msgid "Breaks exisiting package '%s' dependency %s (%s %s)\n"
#~ msgstr "残缺：软件包 '%s' 依赖 %s (%s %s)\n"
